version: '3.1'

services:
  db:
    image: postgres
    container_name: local_pgdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  go-app:
    build: .
    ports:
      - 5000:5000
    restart: always
    environment:
      - PORT=0.0.0.0:5000
      - HOST=db
      - USER=admin
      - PASSWORD=admin
      - DB_NAME=crud_db
    depends_on:
      - db
