version: '3.1'

services:

  db:
    image: postgres
    container_name: local_pgdb
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
